/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bqbrdmcchgzxzkgwpwkv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYnJkbWNjaGd6eHprZ3dwd2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTgwNzEsImV4cCI6MjA3NDM3NDA3MX0.BGe41-z4nD6yuznkB5zp6pUtn7AnNNG4pZH-M50E1aQ"